import { PoolClient } from 'pg';

/**
 * Migration: Create replay_cursors table
 *
 * Provides durable, DB-backed cursor state for IndexerService.replayEvents.
 *
 * Each replay run creates one row in this table when it starts. After every
 * committed batch, the row's `last_committed_offset`,
 * `last_committed_event_id`, and `last_committed_block_height` are updated
 * atomically inside the same batch transaction. A process crash therefore
 * leaves the checkpoint at the last fully committed batch, and a re-run can
 * resume from exactly that position.
 *
 * Design notes:
 *  - `id` is a UUID generated by PostgreSQL (no application-side UUID dep).
 *  - `status` remains `running` until all batches are committed.
 *  - `completed_at` is set to now() when all batches have been committed.
 *    The partial indexes keep live-cursor and latest-checkpoint lookups fast.
 *  - Only one active cursor per (contract_id, ledger) is enforced at the
 *    application layer (concurrent-replay lock), not at the DB level, so that
 *    historical completed rows are retained for auditing.
 */

export async function up(client: PoolClient): Promise<void> {
  console.log('Creating replay_cursors table...');

  await client.query(`
    CREATE TABLE IF NOT EXISTS replay_cursors (
      id                           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      contract_id                  TEXT NOT NULL,
      ledger                       INTEGER NOT NULL,
      from_block                   INTEGER,
      to_block                     INTEGER,
      total_rows                   INTEGER NOT NULL,
      last_committed_offset        INTEGER NOT NULL DEFAULT 0,
      last_committed_event_id      TEXT,
      last_committed_block_height  INTEGER,
      status                       TEXT NOT NULL DEFAULT 'running',
      started_at                   TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at                   TIMESTAMPTZ NOT NULL DEFAULT now(),
      completed_at                 TIMESTAMPTZ
    );
  `);

  // Existing installations may already have replay_cursors from an earlier
  // version of this migration. Add checkpoint observability columns safely.
  await client.query(`
    ALTER TABLE replay_cursors
      ADD COLUMN IF NOT EXISTS last_committed_event_id TEXT,
      ADD COLUMN IF NOT EXISTS last_committed_block_height INTEGER,
      ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'running',
      ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();
  `);

  await client.query(`
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1
          FROM pg_constraint
         WHERE conname = 'replay_cursors_status_check'
      ) THEN
        ALTER TABLE replay_cursors
          ADD CONSTRAINT replay_cursors_status_check
          CHECK (status IN ('running', 'completed'));
      END IF;
    END
    $$;
  `);

  await client.query(`
    CREATE INDEX IF NOT EXISTS idx_replay_cursors_active
      ON replay_cursors (contract_id, ledger)
      WHERE completed_at IS NULL;
  `);

  await client.query(`
    CREATE INDEX IF NOT EXISTS idx_replay_cursors_running
      ON replay_cursors (contract_id, ledger, updated_at DESC)
      WHERE status = 'running' AND completed_at IS NULL;
  `);

  console.log('replay_cursors table created successfully');
}

export async function down(client: PoolClient): Promise<void> {
  console.log('Dropping replay_cursors table...');

  await client.query(`DROP INDEX IF EXISTS idx_replay_cursors_active;`);
  await client.query(`DROP INDEX IF EXISTS idx_replay_cursors_running;`);
  await client.query(`DROP TABLE IF EXISTS replay_cursors;`);

  console.log('replay_cursors table dropped successfully');
}
