/**
 * Migration: replay_cursors table.
 *
 * Previously used a hand-rolled PoolClient runner (migrations/run.ts).
 * Converted to the node-pg-migrate MigrationBuilder convention so all
 * migrations share a single runner and the pgmigrations ledger.
 *
 * Provides durable, DB-backed cursor state for IndexerService.replayEvents.
 *
 * Each replay run creates one row when it starts. After every committed
 * batch, last_committed_offset is updated atomically inside the same batch
 * transaction — a process crash leaves the offset pointing at the last fully
 * committed batch so a re-run can resume from exactly that position.
 *
 * Design notes:
 *  - id is a UUID generated by PostgreSQL (no app-side UUID dependency).
 *  - completed_at is set to now() when all batches are committed. The partial
 *    index WHERE completed_at IS NULL keeps live-cursor lookups fast.
 *  - One active cursor per (contract_id, ledger) is enforced at the
 *    application layer; historical completed rows are retained for auditing.
 */

import type { ColumnDefinitions, MigrationBuilder } from 'node-pg-migrate';

export const shorthands: ColumnDefinitions | undefined = undefined;

/**
 * Create the replay_cursors table and its active-cursor lookup index.
 */
export async function up(pgm: MigrationBuilder): Promise<void> {
  pgm.createTable(
    'replay_cursors',
    {
      id: {
        type: 'uuid',
        primaryKey: true,
        default: pgm.func('gen_random_uuid()'),
      },
      contract_id:           { type: 'text',        notNull: true },
      ledger:                { type: 'integer',      notNull: true },
      from_block:            { type: 'integer' },
      to_block:              { type: 'integer' },
      total_rows:            { type: 'integer',      notNull: true },
      last_committed_offset: { type: 'integer',      notNull: true, default: 0 },
      started_at:            { type: 'timestamptz',  notNull: true, default: pgm.func('now()') },
      completed_at:          { type: 'timestamptz' },
    },
    { ifNotExists: true },
  );

  // Partial index — fast lookup of the active cursor for a given replay job
  pgm.sql(`
    CREATE INDEX IF NOT EXISTS idx_replay_cursors_active
      ON replay_cursors (contract_id, ledger)
      WHERE completed_at IS NULL;
  `);
}

/**
 * Drop the replay_cursors table and its index.
 *
 * ⚠️  Not executed in automated production scripts.
 */
export async function down(pgm: MigrationBuilder): Promise<void> {
  pgm.sql(`DROP INDEX IF EXISTS idx_replay_cursors_active;`);
  pgm.dropTable('replay_cursors', { ifExists: true });
}
