import { MigrationBuilder } from 'node-pg-migrate';

/**
 * Migration: Create replay_cursors table
 *
 * Provides durable, DB-backed cursor state for IndexerService.replayEvents.
 *
 * Each replay run creates one row in this table when it starts.
 * After every committed batch, the row's `last_committed_offset` is updated
 * atomically inside the same batch transaction — meaning a process crash at
 * any point leaves the offset pointing at the last fully committed batch, and
 * a re-run can resume from exactly that position.
 *
 * Design notes:
 *  - `id` is a UUID generated by PostgreSQL (no application-side UUID dep).
 *  - `completed_at` is set to now() when all batches have been committed.
 *    The partial index WHERE completed_at IS NULL keeps the live-cursor lookup fast.
 *  - Only one active cursor per (contract_id, ledger) is enforced at the
 *    application layer (concurrent-replay lock), not at the DB level, so that
 *    historical completed rows are retained for auditing.
 */

export async function up(pgm: MigrationBuilder): Promise<void> {
  pgm.createExtension('pgcrypto', { ifNotExists: true });

  pgm.createTable('replay_cursors', {
    id: { type: 'uuid', primaryKey: true, default: pgm.func('gen_random_uuid()') },
    contract_id: { type: 'text', notNull: true },
    ledger: { type: 'integer', notNull: true },
    from_block: { type: 'integer' },
    to_block: { type: 'integer' },
    total_rows: { type: 'integer', notNull: true },
    last_committed_offset: { type: 'integer', notNull: true, default: 0 },
    started_at: { type: 'timestamp with time zone', notNull: true, default: pgm.func('now()') },
    completed_at: { type: 'timestamp with time zone' },
  }, { ifNotExists: true });

  pgm.createIndex('replay_cursors', ['contract_id', 'ledger'], {
    name: 'idx_replay_cursors_active',
    ifNotExists: true,
    where: 'completed_at IS NULL',
  });
}

/**
 * Drop the durable replay cursor table.
 */
export async function down(pgm: MigrationBuilder): Promise<void> {
  pgm.dropIndex('replay_cursors', ['contract_id', 'ledger'], {
    name: 'idx_replay_cursors_active',
    ifExists: true,
  });
  pgm.dropTable('replay_cursors', { ifExists: true });
}
